export enum Types {
  CART_TO_CART = 'CART_TO_CART',
  REMOVE_FROM_CART = 'REMOVE_FROM_CART',
  RESET_CART = 'RESET_CART',
  SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS',
  SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD',
}
